### ISSUE TITLE
Combined with Inetelephense renaming add two times the same change

### ISSUE THREAD

**Issue by malyutki** [PlusTimeIT/vscode-php-file-refactoring#1]
I've got a problem when installed this extension. I was looking at the possibility to change the namespace with moving file to a different folder, but I've got also Intelephense which has the same renaming functionality and when I'm trying to change the namespace by renaming class from Test to TestNew I'm getting TestNewNew. Is there a chance to fix it or give a possibility to disable this functionality?

**Comment by Kane-R-G** [comment]
@malyutki Yeah, they are likely conflicting at some point - I'll look at adding an option to disable updating namespaces in the next day or so.

**Comment by Kane-R-G** [comment]
version 0.1.3 now has the ability to stop updating the files own type name (class, trait, enum etc).

This should help with any conflicts that might arise with other extension. Let me know if the error still persists after updating.,
